//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_TuttoAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class annunci_vendita
    {
        public string TargaAuto { get; set; }
        public string MailVenditore { get; set; }
        public System.DateTime DataAnnuncio { get; set; }
        public Nullable<System.DateTime> DataVendita { get; set; }
        public double Prezzo { get; set; }
        public string Regione { get; set; }
        public string MailAcquirente { get; set; }
    
        public virtual utenti utenti { get; set; }
        public virtual regioni regioni { get; set; }
        public virtual auto auto { get; set; }
        public virtual utenti utenti1 { get; set; }
    }
}
