//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_TuttoAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class auto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public auto()
        {
            this.annunci_vendita = new HashSet<annunci_vendita>();
            this.contratti_assicurativi = new HashSet<contratti_assicurativi>();
            this.multe = new HashSet<multe>();
        }
    
        public string Targa { get; set; }
        public int AnnoImmatricolazione { get; set; }
        public decimal Kilometraggio { get; set; }
        public int Potenza { get; set; }
        public string Colore { get; set; }
        public string MailProprietario { get; set; }
        public string Alimentazione { get; set; }
        public string CasaProduttrice { get; set; }
        public string NomeModello { get; set; }
    
        public virtual alimentazioni alimentazioni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<annunci_vendita> annunci_vendita { get; set; }
        public virtual utenti utenti { get; set; }
        public virtual modelli modelli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contratti_assicurativi> contratti_assicurativi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<multe> multe { get; set; }
    }
}
