//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_TuttoAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class banche
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public banche()
        {
            this.proposte_finanziamento = new HashSet<proposte_finanziamento>();
        }
    
        public string Nome { get; set; }
        public string Nazione { get; set; }
    
        public virtual nazioni nazioni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proposte_finanziamento> proposte_finanziamento { get; set; }
    }
}
