//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_TuttoAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_produttrici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public case_produttrici()
        {
            this.modelli = new HashSet<modelli>();
        }
    
        public string Nome { get; set; }
        public int AnnoFondazione { get; set; }
        public string NomeFondatore { get; set; }
        public string LinkSitoWeb { get; set; }
        public string Descrizione { get; set; }
        public string Nazione { get; set; }
    
        public virtual nazioni nazioni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modelli> modelli { get; set; }
    }
}
