//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_TuttoAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratti_assicurativi
    {
        public string TargaAuto { get; set; }
        public System.DateTime DataInizio { get; set; }
        public System.DateTime DataFine { get; set; }
        public decimal PercentualeSconto { get; set; }
        public string MailUtente { get; set; }
        public string CasaProduttrice { get; set; }
        public string NomeModello { get; set; }
        public string PartitaIVAAssicurazione { get; set; }
    
        public virtual auto auto { get; set; }
        public virtual utenti utenti { get; set; }
        public virtual offerte_assicurative offerte_assicurative { get; set; }
    }
}
