//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_TuttoAuto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TUTTOAUTOEntities : DbContext
    {
        public TUTTOAUTOEntities()
            : base("name=TUTTOAUTOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alimentazioni> alimentazioni { get; set; }
        public virtual DbSet<annunci_vendita> annunci_vendita { get; set; }
        public virtual DbSet<assicurazioni> assicurazioni { get; set; }
        public virtual DbSet<auto> auto { get; set; }
        public virtual DbSet<banche> banche { get; set; }
        public virtual DbSet<case_produttrici> case_produttrici { get; set; }
        public virtual DbSet<contratti_assicurativi> contratti_assicurativi { get; set; }
        public virtual DbSet<messaggi> messaggi { get; set; }
        public virtual DbSet<modelli> modelli { get; set; }
        public virtual DbSet<multe> multe { get; set; }
        public virtual DbSet<nazioni> nazioni { get; set; }
        public virtual DbSet<offerte_assicurative> offerte_assicurative { get; set; }
        public virtual DbSet<proposte_finanziamento> proposte_finanziamento { get; set; }
        public virtual DbSet<regioni> regioni { get; set; }
        public virtual DbSet<sconti> sconti { get; set; }
        public virtual DbSet<servizi> servizi { get; set; }
        public virtual DbSet<stipulazioni> stipulazioni { get; set; }
        public virtual DbSet<utenti> utenti { get; set; }
    }
}
