//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_TuttoAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class messaggi
    {
        public string MailRicevente { get; set; }
        public string MailMittente { get; set; }
        public int Codice { get; set; }
        public System.DateTime Data { get; set; }
        public string Testo { get; set; }
    
        public virtual utenti utenti { get; set; }
        public virtual utenti utenti1 { get; set; }
    }
}
