//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_TuttoAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class modelli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public modelli()
        {
            this.auto = new HashSet<auto>();
            this.offerte_assicurative = new HashSet<offerte_assicurative>();
        }
    
        public string CasaProduttrice { get; set; }
        public string Nome { get; set; }
        public int AnnoPresentazione { get; set; }
        public string Tipo { get; set; }
        public int Lunghezza { get; set; }
        public int Larghezza { get; set; }
        public int Peso { get; set; }
        public int Altezza { get; set; }
        public int VotoEuroNCAP { get; set; }
        public string NazioneAssemblaggio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auto> auto { get; set; }
        public virtual case_produttrici case_produttrici { get; set; }
        public virtual nazioni nazioni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<offerte_assicurative> offerte_assicurative { get; set; }
    }
}
