//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_TuttoAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class multe
    {
        public int NumeroVerbale { get; set; }
        public System.DateTime DataInfrazione { get; set; }
        public string ViaInfrazione { get; set; }
        public string CittàInfrazione { get; set; }
        public double Costo { get; set; }
        public System.DateTime DataScadenza { get; set; }
        public string Descrizione { get; set; }
        public string MailUtente { get; set; }
        public string TargaAuto { get; set; }
    
        public virtual auto auto { get; set; }
        public virtual utenti utenti { get; set; }
    }
}
