//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_TuttoAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class offerte_assicurative
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public offerte_assicurative()
        {
            this.contratti_assicurativi = new HashSet<contratti_assicurativi>();
            this.servizi = new HashSet<servizi>();
        }
    
        public string CasaProduttrice { get; set; }
        public string NomeModello { get; set; }
        public string PartitaIVAAssicurazione { get; set; }
        public double Premio { get; set; }
        public Nullable<System.DateTime> DataScadenza { get; set; }
        public double Massimale { get; set; }
    
        public virtual assicurazioni assicurazioni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contratti_assicurativi> contratti_assicurativi { get; set; }
        public virtual modelli modelli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servizi> servizi { get; set; }
    }
}
