//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_TuttoAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class proposte_finanziamento
    {
        public int Codice { get; set; }
        public int NumeroRate { get; set; }
        public double ImportoSingolaRata { get; set; }
        public decimal Interessi { get; set; }
        public string Banca { get; set; }
    
        public virtual banche banche { get; set; }
    }
}
