//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_TuttoAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class stipulazioni
    {
        public string PartitaIVAAssicurazione { get; set; }
        public string MailUtente { get; set; }
        public int NumeroContrattiTotali { get; set; }
    
        public virtual assicurazioni assicurazioni { get; set; }
        public virtual utenti utenti { get; set; }
    }
}
