//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_TuttoAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class utenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public utenti()
        {
            this.annunci_vendita = new HashSet<annunci_vendita>();
            this.annunci_vendita1 = new HashSet<annunci_vendita>();
            this.auto = new HashSet<auto>();
            this.contratti_assicurativi = new HashSet<contratti_assicurativi>();
            this.messaggi = new HashSet<messaggi>();
            this.messaggi1 = new HashSet<messaggi>();
            this.multe = new HashSet<multe>();
            this.stipulazioni = new HashSet<stipulazioni>();
        }
    
        public string Nominativo { get; set; }
        public string IndirizzoMail { get; set; }
        public string PasswordAccesso { get; set; }
        public string Tipo { get; set; }
        public string CodiceFiscale { get; set; }
        public string PartitaIVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<annunci_vendita> annunci_vendita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<annunci_vendita> annunci_vendita1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auto> auto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contratti_assicurativi> contratti_assicurativi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<messaggi> messaggi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<messaggi> messaggi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<multe> multe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stipulazioni> stipulazioni { get; set; }
    }
}
